name: Deploy Index production
on:
  push:
    branches:
      - master*

jobs:
  deploy:
    name: Deploy to CloudRun (test and prod)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: vendure

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: pinelab-shops
          service_account_key: ${{ secrets.PINELAB_SHOPS_GCLOUD_KEY }}
          export_default_credentials: true
      - name: Build Docker container
        run: ./build.sh
      - name: Set env vars
        run: 'echo "$SECRET_VARS" > .env'
        env:
          SECRET_VARS: ${{secrets.ENV_PROD}}
      - name: Deploy prod
        run: ./deploy-prod.sh
      - name: Set env vars
        run: 'echo "$SECRET_VARS" > .env.test'
        env:
          SECRET_VARS: ${{secrets.ENV_TEST}}
      - name: Deploy test
        run: ./deploy-test.sh
