name: Deploy Directus
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Directus to CloudRun
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: directus-cms

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: pinelab-shops
          service_account_key: ${{ secrets.PINELAB_SHOPS_GCLOUD_KEY }}
          export_default_credentials: true
      - name: Set KeyFile
        run: 'echo "$KEYFILE" > directus_key.json'
        env:
          KEYFILE: ${{secrets.DIRECTUS_GCLOUD_KEY}}
      - name: Set env vars
        run: 'echo "$SECRET_VARS" > .env'
        env:
          SECRET_VARS: ${{secrets.ENV_DIRECTUS}}
      - name: Build Docker container
        run: ./build.sh
      - name: Deploy
        run: ./deploy.sh