name: Deploy Vendure API and worker to dev only
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to CloudRun
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: vendure

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Authenticate gcloud
        uses: google-github-actions/auth@v0
        with:
          project_id: pinelab-shops
          credentials_json: ${{ secrets.PINELAB_SHOPS_GCLOUD_KEY }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: pinelab-shops
      - name: Build Docker container
        run: ./build.sh
      - name: Export MAIN test env vars
        run: 'echo "$SECRET_VARS" > .env'
        env:
          SECRET_VARS: ${{secrets.ENV_TEST}}
      - name: Deploy MAIN test api
        run: ./deploy-test.sh shops-test pinelab2 1G
      - name: Deploy MAIN test worker
        run: ./deploy-test.sh worker-test pinelab2 1G
      - name: Export WKW env vars
        run: 'echo "$SECRET_VARS" > .env'
        env:
          SECRET_VARS: ${{secrets.ENV_WKW_TEST}}
      - name: Deploy WKW test api
        run: ./deploy-test.sh wkw-test-api pinelab2 1G
      - name: Deploy WKW worker
        run: ./deploy-test.sh wkw-test-worker pinelab2 1G
