name: Deploy Vendure production
on:
  push:
    branches:
      - master*

jobs:
  deploy:
    name: Deploy to CloudRun (test-api)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: vendure

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: pinelab-shops
          service_account_key: ${{ secrets.PINELAB_SHOPS_GCLOUD_KEY }}
          export_default_credentials: true
      - name: Build Docker container
        run: ./build.sh
      - name: Deploy
        run: ./deploy-prod.sh
