name: Deploy Vendure Test envs
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: vendure
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          project_id: pinelab-shops
          credentials_json: ${{ secrets.PINELAB_SHOPS_GCLOUD_KEY }}
      - uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: pinelab-shops
      - name: Build Docker container
        run: ./build.sh

  deploy-main-test:
    needs: [build]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: vendure
    steps:
      - uses: google-github-actions/auth@v0
        with:
          project_id: pinelab-shops
          credentials_json: ${{ secrets.PINELAB_SHOPS_GCLOUD_KEY }}
      - uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: pinelab-shops
      - name: Build Docker container
        run: ./build.sh
      - name: Export MAIN test env vars
        run: 'echo "$SECRET_VARS" > .env'
        env:
          SECRET_VARS: ${{secrets.ENV_TEST}}
      - name: Deploy MAIN test api
        run: ./deploy-test.sh shops-test pinelab2 1G
      - name: Deploy MAIN test worker
        run: ./deploy-test.sh worker-test pinelab2 1G

  deploy-wkw-test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v0
        with:
          project_id: pinelab-shops
          credentials_json: ${{ secrets.PINELAB_SHOPS_GCLOUD_KEY }}
      - uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: pinelab-shops
      - name: Export WKW test env vars
        run: 'echo "$SECRET_VARS" > .env'
        env:
          SECRET_VARS: ${{secrets.ENV_WKW_TEST}}
      - name: Deploy WKW test api
        run: ./deploy-test.sh wkw-test-api pinelab2 1G
      - name: Deploy WKW test worker
        run: ./deploy-test.sh wkw-test-worker pinelab2 1G