name: Test pinelab-storefront with Vendure server
on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: packages/e2e
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build Vendure
        run: cd ../../vendure/ && yarn
      - name: Build Pinelab-storefront
        run: cd ../e2e/pinelab-storefront && yarn
      - name: Build e2e
        run: yarn
      - name: Test
        run: cd ../e2e && yarn jest:e2e
